pimcore:
    workflows:
        workflow:
            label: 'Product Workflow'
            type: 'state_machine'
            supports:
            - 'Pimcore\Model\DataObject\Electronics'
            places:
                new:
                    label: 'New product'
                    color: '#377ea9'
                    permissions:
                        - objectLayout: 6
                rejected:
                    label: 'Rejected product'
                    color: '#28a013'
                update_content:
                    label: 'UpdateProductDetails'
                    title: 'Updating content step'
                    color: '#d9ef36'
                    permissions:
                        - objectLayout: 7
                updateMedia:
                    label: 'UpdateMedia'
                    title: 'Updating  Media step'
                    color: '#d9ef36'
                    permissions:
                        - objectLayout: 8
                updateManufacturer:
                    label: 'UpdateManufacturer'
                    title: 'Updating Manufacturer'
                    color: '#d9ef36'
                    permissions:
                        - objectLayout: 9
                UpdateDealer:
                    label: 'UpdateDealer'
                    title: 'Updating Dealer'
                    color: '#d9ef36'
                    permissions:
                        - objectLayout: 10
                UpdateSalesInfo:
                    label: 'UpdateSalesInfo'
                    title: 'Updating Sales info'
                    color: '#d9ef36'
                    permissions:
                        - objectLayout: 11
                UpdatePricing:
                    label: 'UpdatePricing'
                    title: 'Updating Pricing'
                    color: '#d9ef36'
                    permissions:
                        - objectLayout: 12
                content_prepared:
                    label: 'Content Prepared'
                    title: 'Content ready to publish'
                    color: '#28a013'
                accepted:
                    label: 'Accepted product'
                    color: '#28a013'
                    
            transitions:
                reject_product:
                    from: [new, content_prepared]
                    to: new
                    options:
                        label: 'Reject the product'
                        notes:
                            commentEnabled: false
                            commentRequired: false
                start_processing:
                    from: new
                    to: update_content
                    options:
                        label: 'Start processing the product'
                        notes:
                            commentEnabled: false
                            commentRequired: false
                content_updated:
                    from: update_content
                    to: updateMedia
                    options:
                        label: 'Content up-to-date'
                        notes:
                            commentEnabled: false
                            commentRequired: false
                picture_updated:
                    from: updateMedia
                    to: updateManufacturer
                    options:
                        label: 'Picture up-to-date'
                        notes:
                            commentEnabled: false
                            commentRequired: false
                manufacturer_updated:
                    from: updateManufacturer
                    to: UpdateDealer

                    options:
                        label: 'manufacturer up-to-date'
                        notes:
                            commentEnabled: false
                            commentRequired: false
                Dealer_updated:
                    from: UpdateDealer
                    to:  UpdateSalesInfo
                    options:
                        label: Dealer up-to-date'
                        notes:
                            commentEnabled: false
                            commentRequired: false
                Sales_updated:
                    from: UpdateSalesInfo
                    to:  UpdatePricing
                    # guard: "is_fully_authenticated() and is_granted('ROLE_DataEntry')"
                    options:
                        label: 'sales up-to-date'
                        notes:
                            commentEnabled: false
                            commentRequired: false
                # pricing_updated:
                #     from: UpdatePricing
                #     to:  content_prepared
                #     # guard: "is_fully_authenticated() and is_granted('ROLE_DataEntry')"
                #     options:
                #         label: 'pricing up-to-date'
                #         notes:
                #             commentEnabled: false
                #             commentRequired: false
                
                content_ready:
                     from: UpdatePricing
                     to: content_prepared
                     options:
                        label: 'Content is ready to publish'
                        
                publish:
                    from: content_prepared
                    to: accepted
                    guard: "is_fully_authenticated() and is_granted('ROLE_Reviewer')"
                    options:
                        label: 'Publish the product'
                        notes:
                            commentEnabled: true
                            commentRequired: true
                            
                