pimcore:
    custom_report:
        definitions:
            CustomReport:
                name: CustomReport
                sql: ''
                dataSourceConfig:
                    -
                        sql: 'ProductCategory, count(*)'
                        from: object_5
                        where: ''
                        groupby: ProductCategory
                        type: sql
                columnConfiguration:
                    -
                        name: 'count(*)'
                        display: true
                        export: true
                        order: true
                        width: ''
                        label: ''
                        id: extModel383-1
                    -
                        name: ProductCategory
                        display: true
                        export: true
                        order: true
                        width: ''
                        label: ''
                        id: extModel383-2
                niceName: ''
                group: ''
                groupIconClass: ''
                iconClass: ''
                menuShortcut: true
                reportClass: ''
                chartType: pie
                pieColumn: 'count(*)'
                pieLabelColumn: 'count(*)'
                xAxis: null
                yAxis: {  }
                modificationDate: 1676268077
                creationDate: 1676267087
                shareGlobally: true
                sharedUserNames:
                    - admin
                sharedRoleNames: {  }
